---
title: "A Imunidade Tributária Recíproca e o Transporte de Mercadorias pela ECT"
subtitle: ": Uma Análise Crítica da Decisão do STF no RE 627.051"
author: "Alceu Eilert Nascimento"
date: "2024-08-25"
format:
  docx:
    reference-doc: ufpr_template_artigo.docx
keep_tex: true
geometry: "left=3cm, right=2cm, top=3cm, bottom=2cm"
bibliography: bibliografia.bib
link-citations: TRUE
endnote: no
csl: "ipea.csl"
editor: 
  markdown: 
    wrap: sentence
---

# 1. Introdução

O presente artigo explora as imbricações entre direito e econômica para analisar os efeitos da decisão do Supremo Tribunal Federal no Recurso Extraordinário 627.051, que concedeu imunidade tributária recíproca à Empresa Brasileira de Correios e Telégrafos nas atividades de transporte de mercadorias, suscita importantes questionamentos econômicos e jurídicos.
Embora o tribunal tenha fundamentado sua decisão na ideia de subsídio cruzado e na indissociabilidade do serviço postal essencial com as demais atividades da empresa, argumenta-se que essa análise desconsiderou a presença de um subsídio direto à empresa em suas atividades econômicas desenvolvidas sob regime concorrencial.
Este artigo busca demonstrar que a decisão, ignora a regra constitucional de neutralidade competitiva e livre concorrência, configurando um erro de interpretação constitucional com consequências negativas para o mercado.

# 2. Recurso Extraordinário 627.051

Desde o início dos anos 2000, o Supremo Tribunal Federal (STF) se debrucou sobre diversos casos envolvendo a imunidade recíproca da Empresa Brasileira de Correios e Telégrafos (ECT), ora tratando de tributos municipais, ora de estaduais.
A questão envolvendo os limites da imunidade tributária deferida à ECT já foi objeto de discussão em diversos precedentes do STF, como exemplificam os seguintes julgados: RE nº 407.099/RS, Segunda Turma, Relator o Ministro Carlos Velloso, DJ de 6/8/2004; ACO nº 765/RJ, Tribunal Pleno, Relator o Ministro Marco Aurélio, redator para o acórdão o Ministro Menezes Direito, DJe de 3/9/2009; ADPF nº 46/DF, Relator o Ministro Marco Aurélio, redator para o acórdão o Ministro Eros Grau, DJe de 25/2/2010; e ACO nº 789/PI, Relator o Ministro Marco Aurélio, redator para o acórdão o Ministro Dias Tofoli, DJe de 14/10/2010; dentre outros.

Em 12 de novembro de 2014, o Plenário do STF julgou o Recurso Extraordinário nº 627.051/PE, que estava sob o regime de representativo de controvérsia, passível de ser o leading case sobre a matéria.
A ECT havia interposto o recurso extraordinário questionando decisão do Tribunal Regional Federal da 5ª Região (TRF-5), que determinou que, por ser a ECT uma pessoa jurídica de direito privado, ela se submete às mesmas obrigações tributárias que as empresas privadas.
Por essa razão, o Imposto sobre Operações relativas à Circulação de Mercadorias e sobre Prestações de Serviços de Transporte Interestadual e Intermunicipal e de Comunicação (ICMS) deveria incidir sobre o transporte de mercadorias realizado pela ECT, pois ela não estaria protegida pela imunidade constitucional.

Em sua defesa, a ECT alegou violação ao artigo 150, inciso VI, alínea "a" da Constituição Federal, sustentando que, de acordo com a jurisprudência do STF, a imunidade tributária que lhe é atribuída é geral e irrestrita, aplicável a qualquer imposto estadual.
Argumentou que a atividade de transporte de encomendas não pode ser alvo de incidência do ICMS, pois faz parte do ciclo que compõe a atividade postal.
Nesse sentido, para fins de aplicação da imunidade tributária, não importa qual serviço está sendo prestado, já que todos os recursos obtidos pela ECT são revertidos em favor do serviço postal, destinado à coletividade.
Em preliminar de repercussão geral, buscou demonstrar a relevância da matéria.

Em paralelo, o Estado de São Paulo se manifestou, como *amicus curiae*, argumentando que imunidade restringe-se aos serviços postais constantes nos três incisos do art. 9º da Lei nº 6.538/78[^1].
Assim, os serviços de transporte de mercadorias deveriam sofrer incidência de ICMS, sujeitando a ECT às mesmas condições que as demais empresas de direito privado que prestam o mesmo serviço.

[^1]: Lei nº 6.538/78.
    Art. 9º - São exploradas pela União, em regime de monopólio, as seguintes atividades postais: I - recebimento, transporte e entrega, no território nacional, e a expedição, para o exterior, de carta e cartão-postal; II - recebimento, transporte e entrega, no território nacional, e a expedição, para o exterior, de correspondência agrupada: III - fabricação, emissão de selos e de outras fórmulas de franqueamento postal.

O STF acolheu o argumento da ECT, fundamentando-se na função pública da empresa, no subsídio cruzado entre suas atividades superavitárias (atividades operadas em regime concorrencial) e deficitárias (serviço público) e na necessidade de garantir um serviço postal universal e acessível.
A corte entendeu que os subsídios cruzados permitem à ECT oferecer os serviços postais a preços módicos, contribuindo para exercício dos direitos fundamentais da pessoa humana -- desempenhando um papel crucial ao garantir a privacidade e segurança nas comunicações -- promovendo a integração nacional[@toffoliRecursoExtraordinario6270512014].
Dessa forma, não há comprometimento do *status* de empresa pública prestadora de serviços essenciais e a atividade de transporte de encomendas constitui *conditio sine qua non* para viabilidade de um serviço portal contínuo, universal e de preços módicos.
Destacam que a ECT não está criando uma estrutura para competir, meramente aproveitando dos meios já disponíveis necessários para serviço postal e que a entrega de correspondências e encomendas são fases indissociáveis do serviço postal.

Essa decisão desonerou as atividades comerciais da ECT de uma carga tributária aplicada a seus concorrentes privados.

## 2.2. Referência teórica

A referência teórica para a analise do caso é o princípios da livre concorrência, instrumentalizado na neutralidade competiviva, com foco específico na neutralidade tributária.

Os governos podem criar um ambiente de mercado desigual onde uma empresa estatal compete com empresas privadas, pois têm interesse direto em garantir o sucesso das empresas estatais.
Assim, apesar de seu papel como regulador, o governo pode, de fato, restringir a competição ao conceder às empresas estatais diversos benefícios não oferecidos às empresas privadas.
Embora em algumas áreas esse tratamento preferencial seja direto e óbvio, pode haver também tratamento preferencial indireto por outros meios.
A regulação das empresas estatais pode ser arbitrária, tendo como único princípio norteador do governo a proteção de suas estatais acima de todos os outros objetivos.
Altas barreiras à entrada podem surgir, limitando a capacidade do mercado, através da competição, de servir como um controle sobre a má tomada de decisão das empresas estatais.

Na maioria dos casos, as empresas estatais desfrutam de privilégios e imunidades que não estão disponíveis aos seus concorrentes privados.
Esses privilégios conferem às estatais uma vantagem competitiva sobre seus rivais.
Tais vantagens não são baseadas em melhor desempenho, maior eficiência, melhor tecnologia ou habilidades superiores de gestão, mas são meramente criadas pelo governo e distorcem a competição no mercado.

Por exemplo, o tratamento preferencial do governo na proteção de suas estatais pode assumir a forma de taxas de empréstimo favoráveis em comparação com empresas privadas, reduzindo assim o custo de capital da estatal.
Isso pode ter o efeito de um subsídio implícito.
Os governos podem usar recursos públicos para fornecer taxas de empréstimo mais baixas que as taxas de mercado.

As estatais também podem se beneficiar de regulação discriminatória.
Elas podem não ser obrigadas a pagar impostos ou podem ser imunes à legislação antitruste.
Além disso, as estatais podem se beneficiar de assimetrias de informação, pois têm acesso a dados que não estão disponíveis para concorrentes privados.
Uma estatal que atua em múltiplos produtos também pode usar economias de escala e escopo para criar altas barreiras à entrada que efetivamente impedem a competição por concorrentes eficientes.

Algumas empresas estatais recebem subsídios diretos de seu governo ou se beneficiam de outras formas públicas de assistência financeira para sustentar suas operações comerciais.
Por exemplo, nos Estados Unidos, até 2002, a Amtrak havia recebido mais de US\$ 44 bilhões em subsídios federais diretos desde o início de suas operações [@oecdStateOwnedEnterprisesPrinciple2010].
Tal intervenção governamental reduz os custos operacionais da estatal e fornece a ela uma vantagem competitiva significativa sobre seus rivais privados.

Os subsídios diretos, que envolvem uma transferência direta de dinheiro ao beneficiário, são a forma mais simples, mas possivelmente a menos frequentemente utilizada de apoio a uma estatal.
Os subsídios indiretos são mais sutis e mais comuns, e podem distorcer significativamente a competição entre estatais e seus concorrentes privados.
Subsídio indireto é um termo amplo, que abrange qualquer forma de subsídio que não envolva uma transferência direta de dinheiro.
Por exemplo, os regimes fiscais favoráveis ou isenções de certos impostos que são concedidos às estatais equivalem a subsídios governamentais seletivos.
Essas isenções reduzem artificialmente os custos das estatais e aumentam sua capacidade de precificar de forma mais eficiente do que os concorrentes sujeitos a um regime tributário completo.

A tributação deve minimizar distorções de mercado, garantindo que todos os agentes operem sob condições iguais.
Subsídios diretos ou isenções tributárias injustificadas violam esse princípio ao favorecer artificialmente determinados agentes.
O ordenamento jurídico brasileiro, especialmente o art. 173, da Constituição Federal, determina que empresas públicas que atuem em atividades econômicas devem se submeter ao regime jurídico próprio das empresas privadas, incluindo obrigações tributárias.
A imunidade recíproca é destinada exclusivamente às atividades essenciais, não podendo ser estendida para proteger atividades comerciais.
Esses princípios exigem que qualquer benefício concedido a uma empresa pública seja rigorosamente justificado e alinhado ao interesse público, sem prejuízo à concorrência.

## 2.3. Análise do caso

Embora o STF tenha justificado a imunidade com base no subsídio cruzado, a decisão falha ao ignorar que a imunidade tributária aplicada às atividades econômicas da ECT não é um subsídio cruzado interno, mas sim um subsídio direto estatal, configurado pela isenção de ICMS.

Essa distinção é fundamental.
O não pagamento de ICMS nas atividades de transporte de mercadorias confere à ECT uma vantagem econômica direta sobre seus concorrentes privados, que são obrigados a repassar o tributo aos preços dos serviços.
Isso distorce a competição no mercado, ferindo o princípio da livre concorrência.
Portanto, verifica-se que este subsídio se enciaxa na vedação constitucional, presente no art. 173, § 2º, da Constituição Federal[^2], cujo objetivo é instrumentar a neutralidade competitiva.

[^2]: CF/88.
    Art. 173.
    Ressalvados os casos previstos nesta Constituição, a exploração direta de atividade econômica pelo Estado só será permitida quando necessária aos imperativos da segurança nacional ou a relevante interesse coletivo, conforme definidos em lei.
    \[...\] § 2º As empresas públicas e as sociedades de economia mista não poderão gozar de privilégios fiscais não extensivos às do setor privado

Ademais, não há evidências de que o benefício fiscal aplicado às atividades econômicas da ECT seja indispensável para garantir a sustentabilidade do serviço postal deficitário.
A decisão da corte contém diversas passagens indicando o perfil deficitário da atividade postal, conforme:

> Entre os outros argumentos por mim suscitados no referido RE no 601.392/PR, destaco o reduzido potencial concorrencial dos Correios.
> A obrigatoriedade de prestar serviços em todo o território nacional, mormente onde a atividade se afigura manifestamente deficitária, impede o acúmulo de capital.
> Resta, a toda evidência, frustrada a tese de que a desoneração dá ensejo à uma concorrência desleal [@toffoliRecursoExtraordinario6270512014].

Entretanto, não há qualquer prova nos autos que caracterize este cenário.
Pelo contrário, o que se tem hoje é que 76,6% da receita da ECT é derivada de serviços em regime concorrencial, somando mais de R\$ 15,6 bilhões[^3].

[^3]: Dados das Demonstrações de Resultado do Exercício de 2023 da ECT, Nota 21.1.

A decisão cria uma assimetria de mercado, onde empresas privadas que atuam no setor de transporte de mercadorias enfrentam custos tributários que a ECT evita, gerando um ambiente concorrencial desleal e reduzindo o incentivo à eficiência no setor público.

Desta forma, resta claro que a imunidade recíproca prevista no art. 150, VI, "a", da Constituição tem como objetivo proteger serviços públicos essenciais e não atividades econômicas concorrenciais.
A extensão dessa imunidade a serviços de transporte de mercadorias extrapola sua finalidade constitucional e cria uma interpretação expansiva inadequada.

# 3. Conclusão

A decisão do STF no RE 627.051, ao conceder imunidade tributária recíproca à ECT em suas atividades comerciais, negligenciou princípios econômicos fundamentais e a própria lógica constitucional da imunidade tributária.
O argumento do subsídio cruzado, embora legítimo no âmbito interno da ECT, foi utilizado de forma inadequada para mascarar a existência um subsídio direto, que impacta negativamente a livre concorrência e a neutralidade tributária, violando o art. 173, § 2º, da Constituição Federal.
Este artigo conclui que a decisão do STF errou em sua análise ao não diferenciar entre subsídio cruzado interno e subsídio direto estatal, gerando distorções no mercado e favorecendo injustamente a ECT em suas atividades econômicas.
Uma revisão desse entendimento é necessária para alinhar a interpretação constitucional às boas práticas de regulação econômica e concorrência justa.

# Referências
